@extends('layouts.admin.app')
@section('title', __('WhatsApp Flow Control Centre'))
@push('css_or_js')
<style>
.fc-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.fc-card{padding:20px;border:1px solid var(--v2-border,var(--border-color,#dfe5eb));border-radius:12px;background:var(--v2-panel,var(--card-bg,#fff));height:100%;overflow-wrap:anywhere}.fc-card h2{font-size:18px}.fc-card dl{margin:0}.fc-card dt{font-size:12px;color:var(--v2-text-muted,var(--text-muted,#667781));margin-top:12px}.fc-card dd{margin:3px 0}.fc-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}.fc-tabs a{padding:9px 14px;border:1px solid #dfe5eb;border-radius:20px}.fc-tabs a.active{background:#008069;color:white}.fc-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.fc-phone{max-width:340px;border:8px solid #203632;border-radius:30px;overflow:hidden;margin:auto;background:var(--v2-panel,var(--card-bg,#fff))}.fc-phone header{background:#008069;color:#fff;padding:16px}.fc-phone main{padding:18px}.fc-preview-field{border:1px solid #dfe5eb;border-radius:8px;padding:10px;margin:12px 0}.fc-field-note{font-size:12px;color:var(--v2-text-muted,var(--text-muted,#667781))}.fc-hash{font-family:monospace;font-size:12px;word-break:break-all}.fc-event{padding:12px;border-inline-start:3px solid #008069;margin:8px 0;background:var(--v2-panel,var(--card-bg,#fff))}.fc-state{display:inline-block;padding:4px 10px;border-radius:16px;background:#e0eee9;color:#19564a}.fc-danger{border-inline-start:4px solid #d94040;padding:16px;background:var(--v2-panel,var(--card-bg,#fff));margin:16px 0}.fc-support{white-space:pre-wrap;overflow-wrap:anywhere}.fc-table td{vertical-align:top}.fc-toolbar{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}.fc-mobile-grid{display:grid;grid-template-columns:1fr 340px;gap:24px}@media(max-width:1000px){.fc-grid{grid-template-columns:1fr 1fr}.fc-mobile-grid{grid-template-columns:1fr}}@media(max-width:600px){.fc-grid{grid-template-columns:1fr}}
[data-theme="dark"] .fc-card,[data-theme="dark"] .fc-phone,[data-theme="dark"] .fc-event,[data-theme="dark"] .fc-danger{background:#182823;color:#e2ece7}
</style>
@endpush
@section('content')
@php($tab=request('tab','overview'))
<div class="content container-fluid">
 <div class="fc-toolbar"><div><h1 class="page-header-title">{{ __('WhatsApp Flow Control Centre') }}</h1><p class="text-muted">{{ __('Understand readiness, review changes and recover safely.') }} · {{ app()->environment() }}</p></div>
 @if($ready && $permissions['emergency'])<form method="POST" action="{{ route('admin.whatsapp.flows.emergency') }}">@csrf<button class="btn btn-danger">{{ __('Disable Flow Dispatch') }}</button><small class="d-block text-muted">{{ __('Chat fallback stays enabled') }}</small></form>@endif</div>
 @if(session('flow_notice'))<div class="alert alert-success" role="status">{{ session('flow_notice') }}</div>@endif
 @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
 @unless($definitionValid)<div class="alert alert-danger">{{ __('Definition integrity or validation failed. Lifecycle actions are blocked; emergency disable remains available.') }}</div>@endunless
 @unless($ready)<div class="alert alert-warning">{{ __('Control-centre migrations are not applied. Actions are unavailable until the approved migration runs.') }}</div>@endunless
 <nav class="fc-tabs" aria-label="{{ __('WhatsApp Concierge navigation') }}"><a href="{{ route('admin.whatsapp.ai-dashboard.index') }}">{{ __('Concierge dashboard') }}</a><a href="{{ route('admin.whatsapp.inbox.index') }}">{{ __('WhatsApp Inbox') }}</a><a href="{{ route('admin.whatsapp.operations-center.index') }}">{{ __('Vendor applications') }}</a><a href="{{ route('admin.whatsapp.resume-campaigns.index') }}">{{ __('Approved templates') }}</a><a href="{{ route('admin.whatsapp.ai-providers.index') }}">{{ __('AI providers') }}</a></nav>
 <nav class="fc-tabs" aria-label="{{ __('Flow control sections') }}">@foreach(['overview'=>'Overview','definition'=>'Definition & preview','policies'=>'Policies','test'=>'Test centre','applications'=>'Applications','analytics'=>'Analytics','diagnostics'=>'Diagnostics','settings'=>'Settings','history'=>'Audit & operations'] as $key=>$label)<a class="{{ $tab===$key?'active':'' }}" href="{{ route('admin.whatsapp.flows.index',['tab'=>$key]) }}">{{ __($label) }}</a>@endforeach</nav>
 @if($tab==='overview')
 <div class="fc-grid">
  <section class="fc-card"><h2>{{ __('Meta account') }}</h2><dl><dt>WABA</dt><dd>{{ config('whatsapp-vendor-concierge.api.business_account_id') ?: __('Not configured') }}</dd><dt>Meta application</dt><dd>{{ config('whatsapp-vendor-concierge.api.app_id')?:__('Unknown') }}</dd><dt>{{ __('Sending phone ID') }}</dt><dd>{{ config('whatsapp-vendor-concierge.api.phone_number_id')?:__('Unknown') }}</dd><dt>Graph API</dt><dd>{{ config('whatsapp-vendor-flow.graph_version') }}</dd><dt>Credentials</dt><dd>{{ config('whatsapp-vendor-concierge.api.access_token') ? __('Configured (never shown)') : __('Missing') }}</dd><dt>{{ __('Account / phone health') }}</dt><dd>{{ $readiness['observations']['health']['result']['phone']['status']??__('Unknown') }} / {{ $readiness['observations']['health']['result']['phone']['quality_rating']??__('Unknown') }} · {{ $readiness['observations']['health']['at']??__('No observation') }}</dd></dl><div class="fc-actions">@include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'health','label'=>'Refresh Meta health'])</div></section>
  <section class="fc-card"><h2>{{ config('whatsapp-vendor-flow.sync_name') }}</h2><dl><dt>{{ __('Draft Flow') }}</dt><dd>{{ $summary['synchronization']?->draft_flow_id ?? __('Not synchronized') }}</dd><dt>{{ __('Remote status / observed at') }}</dt><dd>{{ $readiness['observations']['inspect']['result']['status']??($readiness['observations']['remote']['result']['status']??__('Unknown')) }} / {{ $readiness['observations']['inspect']['at']??($readiness['observations']['remote']['at']??'—') }}</dd><dt>{{ __('Definition') }}</dt><dd>{{ $summary['definition_version'] }}</dd><dt>JSON / Data API</dt><dd>{{ $definition['version'] }} / {{ $definition['data_api_version'] }}</dd><dt>{{ __('Local asset SHA-256') }}</dt><dd class="fc-hash">{{ $hash }}</dd><dt>{{ __('Synchronization') }}</dt><dd>{{ $summary['synchronization']?->status ?? 'unknown' }} · {{ $summary['synchronization']?->updated_at ?? '—' }}</dd><dt>{{ __('Published pointer in use') }}</dt><dd>{{ $runtime['flow_id'] ?: __('None') }}</dd><dt>{{ __('Last sync error') }}</dt><dd>{{ $summary['synchronization']?->error_code ?? '—' }}</dd></dl><div class="fc-actions">@include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'inspect','label'=>'Inspect remote'])</div></section>
  <section class="fc-card"><h2>{{ __('Runtime') }}</h2><dl><dt>{{ __('Flow dispatch') }}</dt><dd class="fc-state">{{ $runtime['enabled'] ? __('Enabled') : __('Disabled') }}</dd><dt>{{ __('Rollout') }}</dt><dd>{{ $runtime['rollout_percent'] }}%</dd><dt>{{ __('Test-only mode') }}</dt><dd>{{ count($runtime['test_phones'] ?? []) ? __('Allowlist only') : __('Percentage rollout') }}</dd><dt>{{ __('Approved recipient count') }}</dt><dd>{{ count($runtime['test_phones'] ?? []) }}</dd><dt>{{ __('Chat fallback') }}</dt><dd>{{ $runtime['fallback_to_chat'] ? __('Enabled') : __('Disabled') }}</dd><dt>{{ __('Encryption signature') }}</dt><dd>{{ $readiness['observations']['key_check']['result']['key_signature_status']??__('Unknown') }} / {{ $readiness['observations']['key_check']['at']??'—' }}</dd><dt>{{ __('Encrypted endpoint') }}</dt><dd>{{ $readiness['observations']['ping']['result']['endpoint']??__('Unknown') }} / {{ $readiness['observations']['ping']['at']??'—' }}</dd><dt>{{ __('Registration mode') }}</dt><dd>{{ $runtime['mode'] }}</dd></dl><p class="text-muted mt-3">{{ __('Published does not mean active. Runtime activation is a separate guarded action.') }}</p></section>
 </div>
 <section class="fc-card mt-3"><h2>{{ __('Activation readiness') }}</h2><p>{{ __('Successful observations must be refreshed within 10 minutes before activation. Unknown or stale is not passed.') }}</p>@foreach($readiness['checks'] as $label=>$passed)<p><span class="badge {{ $passed?'badge-success':'badge-warning' }}">{{ $passed?__('Passed'):__('Not ready') }}</span> {{ __($label) }}</p>@endforeach</section><h2 class="h4 mt-4">{{ __('Latest observations and errors') }}</h2>
 @if($summary['synchronization']?->last_error_metadata??null)@php($result=json_decode($summary['synchronization']->last_error_metadata,true))@include('whatsappvendorconcierge::admin.flow_control.result')@endif
 @foreach($operations->take(8) as $op)@php($result=json_decode($op->result??'{}',true))<div class="fc-event"><strong>{{ $op->action }} · {{ $op->state }}</strong> <small>{{ $op->updated_at }}</small>@include('whatsappvendorconcierge::admin.flow_control.result')</div>@endforeach
 @elseif($tab==='definition')
 <div class="fc-actions">@include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'local','label'=>'Validate locally']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'create','label'=>'Create / recover draft']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'upload','label'=>'Upload reviewed asset']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'remote','label'=>'Validate remotely']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'compare','label'=>'Compare remote definition']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'publish','label'=>'Publish'])</div>
 <p class="text-muted mt-3">{{ __('Published definitions are immutable. Security fields, consent statements and server mappings are locked. Preview is illustrative; Meta rendering must be verified on a controlled device.') }}</p>
 @foreach($definition['screens'] as $screen)<details class="fc-card mb-3" {{ $loop->first?'open':'' }}><summary><strong>{{ $loop->iteration }}. {{ $screen['title'] }} · {{ $screen['id'] }}</strong></summary><div class="fc-mobile-grid mt-3"><div>@include('whatsappvendorconcierge::admin.flow_control.fields',['nodes'=>$screen['layout']['children'],'screen'=>$screen])<p class="text-muted">{{ __('Destination: server allowlist → FlowFieldMapper → VendorSelfRegistrationService. Dynamic options and policy versions are revalidated on submission.') }}</p></div><div class="fc-phone"><header>WhatsApp · {{ $screen['title'] }}</header><main>@include('whatsappvendorconcierge::admin.flow_control.fields',['nodes'=>$screen['layout']['children'],'screen'=>$screen,'preview'=>true])</main></div></div></details>@endforeach
 @if($ready && $definitionValid && $permissions['drafts'])<details class="fc-card"><summary>{{ __('Edit presentation — immutable new revision') }}</summary><form method="POST" action="{{ route('admin.whatsapp.flows.presentation') }}">@csrf<input type="hidden" name="asset_hash" value="{{ $hash }}">@foreach(app(\Modules\WhatsAppVendorConcierge\app\Services\FlowControl\Presentation::class)->editable($definition) as $path=>$text)<div class="form-group mt-3"><label for="presentation-{{ $loop->index }}">{{ $path }}</label><input type="hidden" name="changes[{{ $loop->index }}][path]" value="{{ $path }}"><input id="presentation-{{ $loop->index }}" name="changes[{{ $loop->index }}][text]" class="form-control" maxlength="80" value="{{ $text }}"></div>@endforeach<label for="presentation-confirm">{{ __('Review changed text, then type SAVE REVISION. Legal statements and all structure remain locked.') }}</label><input name="confirmation" id="presentation-confirm" class="form-control" required><button class="btn btn-primary mt-3">{{ __('Save new revision') }}</button></form></details>
 <details class="fc-card mt-3"><summary>{{ __('Select or restore a reviewed definition') }}</summary><p>{{ __('Selecting disables dispatch. Active unconsumed sessions must finish or expire first. Create and validate a separate draft before publication; existing published Flow is retained.') }}</p><form method="POST" action="{{ route('admin.whatsapp.flows.select-revision') }}">@csrf<label for="fc-revision">{{ __('Reviewed version') }}</label><select name="version" id="fc-revision" class="form-control"><option>vendor-onboarding-2026-10-07.1</option>@foreach(\Illuminate\Support\Facades\DB::table('wa_flow_definition_revisions')->orderByDesc('created_at')->get() as $revision)<option>{{ $revision->version }}</option>@endforeach</select><label for="fc-select-confirm">{{ __('Type SELECT REVISION') }}</label><input name="confirmation" id="fc-select-confirm" class="form-control" required><button class="btn btn-primary mt-3">{{ __('Select with dispatch disabled') }}</button></form></details>@endif
 @if($ready && $permissions['publish'])<details class="fc-card mt-3"><summary>{{ __('Retire an obsolete published Flow') }}</summary><p>{{ __('Active sessions, the current pointer and the last working published Flow are protected. Only IDs recorded by synchronization can be targeted.') }}</p><form method="POST" action="{{ route('admin.whatsapp.flows.deprecate') }}">@csrf<input type="hidden" name="nonce" value="{{ $nonce }}"><input type="hidden" name="asset_hash" value="{{ $hash }}"><input type="hidden" name="review_token" value="{{ $confirmation }}"><label>{{ __('Recorded published Flow') }}<select name="flow_id" class="form-control">@foreach(\Illuminate\Support\Facades\DB::table('wa_vendor_flow_sync')->whereNotNull('published_flow_id')->get() as $record)<option value="{{ $record->published_flow_id }}">{{ $record->definition_version }} / {{ $record->published_flow_id }}</option>@endforeach</select></label><label>{{ __('Type DEPRECATE followed by the selected Flow ID') }}<input name="confirmation" class="form-control" required></label><button class="btn btn-danger mt-3">{{ __('Queue obsolete Flow retirement') }}</button></form></details>@endif
 @elseif($tab==='settings')
 <section class="fc-card"><h2>{{ __('Runtime and approved test settings') }}</h2><p>{{ __('Changing credentials, policy wording or a published definition is not a runtime setting. Those remain protected by their separate contracts.') }}</p>
 @if($ready && $permissions['settings'] && $permissions['rollout'])<form method="POST" action="{{ route('admin.whatsapp.flows.settings') }}">@csrf @method('PUT')<div class="fc-grid"><div><label for="fc-enabled">{{ __('Dispatch') }}</label><select name="enabled" id="fc-enabled" class="form-control"><option value="0" @selected(!$runtime['enabled'])>Disabled</option><option value="1" @selected($runtime['enabled'])>Enabled</option></select><label for="fc-rollout" class="mt-3">{{ __('Rollout percentage') }}</label><input id="fc-rollout" name="rollout_percent" type="number" min="0" max="100" class="form-control" value="{{ $runtime['rollout_percent'] }}"></div><div><label for="fc-pointer">{{ __('Confirmed published Flow ID') }}</label><input id="fc-pointer" class="form-control" name="flow_id" value="{{ $runtime['flow_id'] }}"><label for="fc-ttl" class="mt-3">{{ __('Session lifetime (minutes)') }}</label><input id="fc-ttl" type="number" min="10" max="1440" class="form-control" name="session_minutes" value="{{ $runtime['session_minutes'] }}"></div><div><label for="fc-phones">{{ __('Explicitly approved controlled recipients (international digits, comma-separated)') }}</label><textarea id="fc-phones" name="test_phones" class="form-control">{{ implode(',',$runtime['test_phones']??[]) }}</textarea><small>{{ __('An allowlist is not proof of Meta recipient verification or an open messaging window.') }}</small></div></div><label class="mt-3" for="fc-save">{{ __('Type SAVE SETTINGS to confirm') }}</label><input id="fc-save" name="confirmation" class="form-control" required autocomplete="off"><label for="fc-live-proof" class="mt-3">{{ __('For public rollout only: type I VERIFIED LIVE ONBOARDING after completing the controlled end-to-end test') }}</label><input id="fc-live-proof" name="live_validation" class="form-control" autocomplete="off"><button class="btn btn-primary mt-3">{{ __('Save guarded settings') }}</button></form>@else<p>{{ __('Additional settings and rollout permissions are required.') }}</p>@endif
 </section>
 @if($ready && $permissions['settings'] && $permissions['recovery'])<section class="fc-card mt-3"><h2>{{ __('Private media limits and cleanup') }}</h2><p>{{ __('Cleanup is disabled by default. Legal evidence and administrative audits are never deleted. Analytics retention is optional; deletion reduces historical funnel coverage.') }}</p><form method="POST" action="{{ route('admin.whatsapp.flows.limits') }}">@csrf @method('PUT')<div class="fc-grid">@foreach(['max_image_bytes'=>'Maximum image bytes','max_document_bytes'=>'Maximum document bytes','max_dimension'=>'Maximum image dimension','max_pixels'=>'Maximum image pixels','abandonment_hours'=>'Expired draft grace period (hours)'] as $key=>$label)<label>{{ __($label) }}<input type="number" class="form-control" name="{{ $key }}" value="{{ $runtime[$key] }}" required></label>@endforeach<label>{{ __('Cleanup cadence') }}<select name="cleanup_schedule" class="form-control">@foreach(['disabled','hourly','daily'] as $cadence)<option @selected($runtime['cleanup_schedule']===$cadence)>{{ $cadence }}</option>@endforeach</select></label><label>{{ __('Analytics retention days (blank preserves history)') }}<input type="number" name="analytics_retention_days" class="form-control" min="1" max="3650" value="{{ $runtime['analytics_retention_days'] }}"></label></div><label>{{ __('Type SAVE LIMITS AND CLEANUP') }}<input name="confirmation" class="form-control" required></label><button class="btn btn-primary mt-3">{{ __('Save bounded maintenance policy') }}</button></form></section>@endif
 @if($ready && (int)auth('admin')->user()->role_id===1)<section class="fc-card mt-3"><h2>{{ __('Role permissions') }}</h2><form method="POST" action="{{ route('admin.whatsapp.flows.permissions') }}">@csrf @method('PUT')<label for="fc-role">{{ __('Existing role ID (not super-admin)') }}</label><input id="fc-role" type="number" min="2" name="role_id" class="form-control" required><div class="fc-actions">@foreach(array_keys($permissions) as $p)<label><input type="checkbox" name="permissions[]" value="{{ $p }}"> {{ ucfirst(str_replace('_',' ',$p)) }}</label>@endforeach</div><label for="fc-grant">{{ __('Type GRANT PERMISSIONS; replaces this role’s Flow grants') }}</label><input id="fc-grant" name="confirmation" class="form-control" required><button class="btn btn-primary mt-3">{{ __('Save permissions') }}</button></form></section>@endif
 @elseif($tab==='policies')
 <div class="fc-actions"><form method="POST" action="{{ route('admin.whatsapp.flows.policy-integrity') }}">@csrf<button class="btn btn-primary" @disabled(!$ready || !$permissions['policies'])>{{ __('Verify current policy integrity') }}</button></form></div>
 @foreach($policies as $policy)<section class="fc-card mt-3"><h2>{{ $policy->policy }} · {{ $policy->locale }}</h2><dl><dt>{{ __('Immutable version') }}</dt><dd>{{ $policy->version }}</dd><dt>{{ __('Effective / retired') }}</dt><dd>{{ $policy->effective_at }} / {{ $policy->retired_at ?? '—' }}</dd><dt>{{ __('Archive SHA-256') }}</dt><dd class="fc-hash">{{ $policy->content_hash }}</dd><dt>{{ __('Acceptance evidence rows') }}</dt><dd>{{ $acceptances[$policy->id]??0 }}</dd><dt>{{ __('Current selection') }}</dt><dd>{{ config('registration-policies.current.'.$policy->locale.'.'.$policy->policy)===$policy->version ? __('Current') : __('Archived') }}</dd><dt>{{ __('Document') }}</dt><dd><a href="{{ route('whatsapp.policy-document',['version'=>$policy->version]) }}" target="_blank" rel="noopener noreferrer">{{ __('Open verified immutable archive') }}</a></dd></dl><p class="text-muted mt-3">{{ __('Published policy wording and acceptance evidence cannot be edited or deleted here.') }}</p></section>@endforeach
 @if($ready && $permissions['policies'] && $permissions['publish'])
 <details class="fc-card mt-3"><summary>{{ __('Publish a new approved immutable policy version') }}</summary><p>{{ __('Use approved wording only. Existing published records and acceptance evidence cannot be overwritten. Publication does not select the document automatically. Reviewed locale: English.') }}</p><form method="POST" action="{{ route('admin.whatsapp.flows.policy-publish') }}">@csrf<label>{{ __('Policy kind') }}<select class="form-control" name="kind"><option value="terms">Terms agreement</option><option value="privacy">Privacy notice acknowledgment</option></select></label><label for="policy-version">{{ __('New unique immutable version') }}</label><input id="policy-version" name="version" class="form-control" required pattern="[a-zA-Z0-9_-]{1,100}"><label for="policy-document">{{ __('Exact approved UTF-8 HTML document (maximum 4 MiB)') }}</label><textarea id="policy-document" name="document" class="form-control" rows="10" required></textarea><label for="policy-confirm">{{ __('Review exact wording, then type PUBLISH POLICY') }}</label><input id="policy-confirm" name="confirmation" class="form-control" required><button class="btn btn-primary mt-3">{{ __('Publish immutable archive') }}</button></form></details>
 <details class="fc-card mt-3"><summary>{{ __('Select shared current policy versions') }}</summary><p>{{ __('Applies to canonical web/API/Flow registration while this module is enabled. Deploy matching core policy configuration before removing the module. Active Flow drafts must finish or expire; dispatch is disabled on selection.') }}</p><form method="POST" action="{{ route('admin.whatsapp.flows.policy-select') }}">@csrf<label>{{ __('Terms') }}<select name="terms" class="form-control">@foreach($policies->where('policy','terms')->where('locale','en') as $p)<option @selected(config('registration-policies.current.en.terms')===$p->version)>{{ $p->version }}</option>@endforeach</select></label><label>{{ __('Privacy notice') }}<select name="privacy" class="form-control">@foreach($policies->where('policy','privacy')->where('locale','en') as $p)<option @selected(config('registration-policies.current.en.privacy')===$p->version)>{{ $p->version }}</option>@endforeach</select></label><label for="policy-selection-confirm">{{ __('Type SELECT SHARED POLICIES') }}</label><input id="policy-selection-confirm" name="confirmation" class="form-control" required><button class="btn btn-primary mt-3">{{ __('Select verified policies with Flow disabled') }}</button></form></details>@endif
 @elseif($tab==='applications')
 <a class="btn btn-primary" href="{{ route('admin.whatsapp.flows.applications') }}">{{ __('Open Flow applications') }}</a><a class="btn btn-outline-primary" href="{{ route('admin.whatsapp.operations-center.index') }}">{{ __('Chat applications and handoff') }}</a><a class="btn btn-outline-secondary" href="{{ route('admin.whatsapp.stuck-applications.index') }}">{{ __('Stuck applications') }}</a>
 @elseif($tab==='test')
 <section class="fc-card"><h2>{{ __('Controlled recipient preflight') }}</h2><p>{{ __('Check account identity, service window, published state and allowlist before any send. Existing vendors are never overwritten.') }}</p><form method="POST" action="{{ route('admin.whatsapp.flows.test-check') }}">@csrf<label for="fc-recipient">{{ __('Controlled number (international digits)') }}</label><input id="fc-recipient" name="recipient" class="form-control" required pattern="[1-9][0-9]{7,14}" autocomplete="off"><button class="btn btn-primary mt-3" @disabled(!$permissions['test_send'])>{{ __('Check eligibility — no message') }}</button></form></section>
 @elseif($tab==='analytics')
 <form method="GET" class="fc-actions mb-3"><input type="hidden" name="tab" value="analytics"><label>{{ __('From') }}<input type="date" name="from" value="{{ $analytics['from']??'' }}" class="form-control"></label><label>{{ __('To') }}<input type="date" name="to" value="{{ $analytics['to']??'' }}" class="form-control"></label><button class="btn btn-primary">{{ __('Apply cohort') }}</button></form><section class="fc-card"><h2>{{ __('Observed Flow funnel') }}</h2><p>{{ __('Distinct sessions. Opens and progress are counted only when the data endpoint observes them; no inferred screen visits.') }}</p>@foreach($analytics['events']??[] as $event)<div class="fc-event"><strong>{{ ucfirst(str_replace('_',' ',$event->event)) }}</strong> {{ $event->sessions }}<progress class="d-block w-100" max="{{ max(1,$analytics['started']??1) }}" value="{{ $event->sessions }}" aria-label="{{ $event->event }}"></progress></div>@endforeach<p>{{ __('Completion rate') }}: {{ $analytics['completion_percent']??'—' }}%</p><p>Flow: {{ $analytics['completed']??0 }} / {{ $analytics['started']??0 }} · Chat: {{ $analytics['chat_completed']??0 }} / {{ $analytics['chat_started']??0 }} ({{ $analytics['chat_completion_percent']??'—' }}%). {{ __('Mean Flow completion time') }}: {{ $analytics['average_seconds']??'—' }} seconds.</p><p>{{ __('Cohorts use session creation date, completed by the observation time. Chat excludes sessions associated with a Flow. No claim of equivalent traffic or causal uplift.') }}</p></section>
 @elseif($tab==='diagnostics')
 <section class="fc-card"><h2>{{ __('Diagnostics') }}</h2>@foreach($diagnostics as $label=>$value)<div class="fc-event"><strong>{{ ucfirst(str_replace('_',' ',$label)) }}</strong><pre class="text-wrap">{{ is_scalar($value)?$value:json_encode($value,JSON_PRETTY_PRINT) }}</pre></div>@endforeach<dl><dt>{{ __('Recent submissions (24h)') }}</dt><dd>{{ $summary['recent_submissions']??0 }}</dd><dt>{{ __('Expired unconsumed drafts') }}</dt><dd>{{ $summary['expired_drafts']??0 }}</dd><dt>{{ __('Orphaned staged files') }}</dt><dd>{{ $summary['orphaned_media']??0 }}</dd><dt>{{ __('Worker / endpoint observation') }}</dt><dd>{{ __('Unknown until observed; queueing is not proof of worker execution.') }}</dd></dl><div class="fc-actions">@include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'token_audit','label'=>'Audit authentication eligibility']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'key_check','label'=>'Check encryption signature']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'health','label'=>'Check connection']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'ping','label'=>'Test encrypted endpoint ping']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'subscriptions','label'=>'Check subscriptions']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'key_configure','label'=>'Configure matching public key']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'reconcile_preview','label'=>'Preview orphan reconciliation']) @include('whatsappvendorconcierge::admin.flow_control.operation',['action'=>'reconcile','label'=>'Reconcile unowned staged images']) @if($permissions['diagnostics'] && $ready)<a class="btn btn-outline-primary" href="{{ route('admin.whatsapp.flows.report') }}">{{ __('Download support summary') }}</a><button type="button" class="btn btn-outline-secondary" id="fc-copy-support">{{ __('Copy support summary') }}</button>@endif</div><p class="text-muted mt-3">{{ __('No arbitrary commands, SQL or unrestricted logs are exposed.') }}</p></section>
 @elseif($tab==='history')
 <section class="fc-card"><h2>{{ __('Lifecycle operations') }}</h2><p>{{ __('Refresh to follow queued → running → succeeded/failed. A running operation without a result needs remote inspection before retrying.') }}</p>@foreach($operations as $op)@php($result=json_decode($op->result??'{}',true))<div class="fc-event"><strong>{{ $op->action }} · {{ $op->state }} · {{ $op->target }}</strong><small class="d-block">{{ $op->id }} · {{ $op->updated_at }}</small>@include('whatsappvendorconcierge::admin.flow_control.result')@if($permissions['diagnostics'] && in_array($op->action,['inspect','compare','health','local','remote','key_check','ping','subscriptions','reconcile_preview'],true) && $op->state!=='succeeded')<form method="POST" action="{{ route('admin.whatsapp.flows.retry-operation',$op->id) }}">@csrf<label>{{ __('Type RETRY for this observation only') }}<input name="confirmation" required class="form-control"></label><button class="btn btn-outline-primary">{{ __('Retry observation') }}</button></form>@endif</div>@endforeach @if($ready){{ $operations->withQueryString()->links() }}@endif</section>
 <section class="fc-card mt-3"><h2>{{ __('Immutable administrative audit') }}</h2><table class="table fc-table"><thead><tr><th>Time</th><th>Administrator</th><th>Action / target</th><th>Outcome</th><th>Safe changes / error metadata</th></tr></thead><tbody>@foreach($audit as $row)<tr><td>{{ $row->created_at }}</td><td>#{{ $row->admin_id }}</td><td>{{ $row->action }} / {{ $row->target??'—' }}</td><td>{{ $row->outcome }}</td><td><pre class="text-wrap">{{ $row->safe_values }}</pre></td></tr>@endforeach</tbody></table>@if($ready){{ $audit->withQueryString()->links() }}@endif</section>
 @endif
</div>
<div class="modal fade" id="fc-confirm" tabindex="-1" role="dialog" aria-labelledby="fc-confirm-title"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h2 id="fc-confirm-title" class="h4">{{ __('Review lifecycle operation') }}</h2><button class="close" data-dismiss="modal" aria-label="Close">&times;</button></div><form method="POST" action="{{ route('admin.whatsapp.flows.action') }}">@csrf<input type="hidden" name="review_token" value="{{ $confirmation }}"><input type="hidden" name="action" id="fc-action"><input type="hidden" name="nonce" value="{{ $nonce }}"><input type="hidden" name="asset_hash" value="{{ $hash }}"><div class="modal-body"><p id="fc-action-label"></p><dl><dt>Flow</dt><dd>{{ config('whatsapp-vendor-flow.sync_name') }} / {{ $summary['synchronization']?->draft_flow_id??'new draft' }}</dd><dt>WABA / phone ID</dt><dd>{{ config('whatsapp-vendor-concierge.api.business_account_id') }} / {{ config('whatsapp-vendor-concierge.api.phone_number_id') }}</dd><dt>{{ __('Configured encryption public-key SHA-256') }}</dt><dd class="fc-hash">{{ $readiness['public_key_hash']??__('Unavailable') }}</dd><dt>Environment / local validation</dt><dd>{{ app()->environment() }} / {{ $definitionValid?'passed':'failed' }}</dd><dt>Remote validation</dt><dd>{{ $summary['synchronization']?->status??'unknown' }}</dd><dt>Definition hash</dt><dd class="fc-hash">{{ $hash }}</dd></dl><p>{{ __('Publication keeps dispatch unchanged. Previous working pointer is retained on failure.') }}</p><label for="fc-confirm-text" id="fc-confirm-label">{{ __('Type the operation name to confirm') }}</label><input class="form-control" id="fc-confirm-text" name="confirmation" autocomplete="off"></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Cancel') }}</button><button class="btn btn-primary">{{ __('Queue confirmed operation') }}</button></div></form></div></div></div>
@endsection
@push('script_2')<script>
$(function(){ $('#fc-copy-support').on('click', async function(){try {const r=await fetch(@json(route('admin.whatsapp.flows.report')),{credentials:'same-origin'});if(!r.ok || !(r.headers.get('content-type')||'').includes('application/json'))throw new Error();await navigator.clipboard.writeText(await r.text());toastr.success('Redacted support summary copied.');}catch(e){toastr.error('Copy unavailable. Use the download link.');}}); $('.fc-operation').on('click',function(){const a=this.dataset.action;$('#fc-action').val(a);$('#fc-action-label').text(this.textContent);$('#fc-confirm-label').text('Type '+a.toUpperCase()+' for a mutation; read-only checks need no typed confirmation.');$('#fc-confirm-text').val('');$('#fc-confirm').modal('show');}); });
</script>@endpush
