<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f3f6f5;font-family:Arial,sans-serif;color:#24352e">
<div style="max-width:620px;margin:24px auto;background:#fff;border-radius:12px;overflow:hidden">
<div style="background:#087e68;color:white;padding:28px"><h1 style="margin:0;font-size:26px">Your shop is ready for you</h1><p style="margin-bottom:0">Welcome to MyTijaara, {{ $d['name'] }}.</p></div>
<div style="padding:28px;line-height:1.65"><p>Hello,</p><p>Thank you for building your business with MyTijaara. Your vendor dashboard gives you access to the tools you may not yet be able to use through WhatsApp.</p>
<table style="width:100%;border-collapse:collapse"><tr><td>Business</td><td><strong>{{ $d['name'] }}</strong></td></tr><tr><td>Store ID</td><td>{{ $d['id'] }}</td></tr><tr><td>Module</td><td>{{ $d['module'] }}</td></tr><tr><td>Login email</td><td>{{ $d['email'] }}</td></tr><tr><td>Dispatch address</td><td>{{ $d['address'] ?? 'See dashboard' }}</td></tr><tr><td>Plan</td><td>{{ $d['plan'] ?? 'See dashboard' }}</td></tr><tr><td>Delivery</td><td>{{ $d['delivery'] }}</td></tr></table>
<p style="margin:26px 0"><a href="{{ $d['login_url'] }}" style="display:inline-block;background:#087e68;color:white;text-decoration:none;padding:12px 22px;border-radius:6px">Open your vendor dashboard</a></p><p>Your permanent login link:<br><a href="{{ $d['login_url'] }}">{{ $d['login_url'] }}</a></p>
<p>Sign in with the email above and the password you set during registration. If you cannot remember it, use <strong>Forgot Password</strong> on the login page. We will never ask you to send your password in WhatsApp or email.</p>
<h2 style="font-size:20px">What to do next</h2><ol><li>Check your shop information, logo, opening hours and contact details.</li><li>Add or update products, photos, prices and stock.</li><li>Review orders and keep customers informed as you fulfil them.</li><li>Review your delivery charges and arrange reliable delivery. Store-managed delivery lets you use your own arrangements; please still update order statuses and complete required delivery verification.</li></ol>
<h2 style="font-size:20px">Keep your shop one tap away</h2><p><strong>Android:</strong> open the login link in Chrome, tap the three-dot menu and choose <em>Add to Home screen</em> (or <em>Install app</em>, if offered).</p><p><strong>iPhone:</strong> open it in Safari, tap Share, then <em>Add to Home Screen</em>. Menu names may vary by browser.</p>
<p>We are working hard on a dedicated vendor mobile app and hope to make it available soon. Thank you for bearing with us; we will announce its availability when it is ready. Your browser dashboard is available in the meantime.</p>
<p>Need a person? <a href="{{ $d['support_url'] }}">Chat with MyTijaara Support</a>. The support chat is separate, so you can continue using the concierge.</p><p>Thank you for being part of MyTijaara.<br><strong>The MyTijaara Team</strong></p></div></div></body></html>
